server:
  port: 8762

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    #应用为注册中心，所以设置为false,代表不向注册中心注册自己。
    registerWithEureka: false
    #由于注册中心的职责就是维护服务实例，它并不需要去检索服务， 所以也设置为 false
    fetchRegistry: false
    service-url:
    # 安全校验
      #defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka,http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8761/eureka
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@registry:8761/eureka
#       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#       defaultZone: http://localhost:8782/eureka,http://localhost:8781/eureka
  server:
      waitTimeInMsWhenSyncEmpty: 0
      enable-self-preservation: false
spring:
  security:
    user:
      name: admin
      password: admin
