server:
  port: 8791

spring:
  application:
    name: ribbon-consumer

eureka:
  client:
    healthcheck:
        enabled: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka

