server:
  port: 9090
spring:
  application:
    name: local-grpc
grpc:
  client:
    local-grpc-server:
      host:
      - ${LOCAL-GRPC-HOST:127.0.0.1}
      port:
      - 9898
      enableKeepAlive: true
      keepAliveWithoutCalls: true
  server:
      port: 9898
