// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `hello.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.bruce.ice.Demo;

import com.zeroc.Ice.Object;

import java.util.Map;

public class _HelloPrxI extends com.zeroc.Ice._ObjectPrxI implements HelloPrx, Object {
    public static final long serialVersionUID = 0L;


    @Override
    public String SayHello(String username) {
        return ("Hello "+username  );
    }

    @Override
    public String SayHello(String username, Map<String, String> context) {
        return ("Hello "+username  );
    }
}
