server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    #应用为注册中心，所以设置为false,代表不向注册中心注册自己。
    registerWithEureka: false
    #由于注册中心的职责就是维护服务实例，它并不需要去检索服务， 所以也设置为 false
    fetchRegistry: false
    service-url:
    # 安全校验
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@registrya:8762/eureka
#       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#       defaultZone: http://localhost:8782/eureka,http://localhost:8781/eureka
  server:
      #在Eureka服务器获取不到集群里对等服务器上的实例时，需要等待的时间，单位为毫秒，默认为1000 * 60 * 5
      waitTimeInMsWhenSyncEmpty: 0
      ##剔除失效服务间隔
      enable-self-preservation: false
      #剔除失效服务间隔
      eviction-interval-timer-in-ms: 2000
spring:
  security:
    user:
      name: admin
      password: admin