spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

##-----------------------------------------------------分割线----------------------------------------------------------------##


#1.x版本使用jedis,2.x版本使用lettuce,参考地址:https://blog.csdn.net/guokezhongdeyuzhou/article/details/79789629
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    lettuce:
      pool:
        max-idle: 10
        min-idle: 1
        max-active: 10
        max-wait: -1ms
##-----------------------------------------------------分割线----------------------------------------------------------------##
#日志配置

logging:
  level:
    org.springframework.web: DEBUG,CONSOLE
  config: classpath:logback-dev.xml
##-----------------------------------------------------分割线----------------------------------------------------------------##

#查看springboot开启了哪些配置
debug: true
#server配置
server:
  port: 8080 #配置程序端口,默认为8080
  session-timeout: 5000 #用户会话session过期时间,以秒为单位
  servlet:
      context-path: /dev

##-----------------------------------------------------分割线----------------------------------------------------------------##
#actuator监控配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 10111
    servlet:
      context-path: /
    ssl:
      enabled: false
  endpoint:
    health:
      show-details: always


##-----------------------------------------------------分割线----------------------------------------------------------------##
#自定义参数
info:
  env:
    param: dev
    randomValue: ${random.value}  #自定义随机数
    randomNum: ${random.int}