server:
  port: 8782


eureka:
  client:
    service-url:
     defaultZone: http://admin:admin@localhost:8761/eureka
#     defaultZone: http://localhost:8781/eureka
spring:
  application:
    name: provider

