spring:
  application:
    name: config-server #对应配置文件规则中的{application} 部分。
  security:
    user:
      name: admin
      password:  '{cipher}78c2c6ceb5dd96e3475b493a8acf8aeb05aafb35168c31f3a3888d3c23ee413a'
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BruceWhiteBai/cloudconfig.git
          username: BruceWhiteBai #git 仓库设置为private 时需要配置用户名密码 使用 curl  http://localhost:8888/encrypt -d 加密
          password: '{cipher}ff7c8aa7b281639a77d32b475e784b55956aee2ffbb0276a7f6521375a48069d'
          searchPaths: config-repo
#        health: #todo 添加健康监测
#          repositories:
      label: config_1 #对应配置文件规则中的{label} 部分。
      profile: dev  #对应配置文件规则中的{profile} 部分。
    stream:
      kafka:
        binder:
          brokers:  localhost:9092
          zk-nodes: 192.168.99.100:2181
#<!--bus config -->
#  rabbitmq:
#    host: 192.168.99.100
#    port: 5672
#    username: springcloud
#    password: 123456

#Kafka的服务端列表，默认localhost
#spring.cloud.stream.kafka.binder.brokers=localhost:9092
#Kafka服务端的默认端口，当brokers属性中没有配置端口信息时，就会使用这个默认端口，默认9092
#spring.cloud.stream.kafka.binder.defaultBrokerPort=9092
#Kafka服务端连接的ZooKeeper节点列表，默认localhost
#spring.cloud.stream.kafka.binder.zkNodes=192.168.99.100:2181
#ZooKeeper节点的默认端口，当zkNodes属性中没有配置端口信息时，就会使用这个默认端口，默认2181
#spring.cloud.stream.kafka.binder.defaultZkPort=2181



server:
  port: 8888


