spring:
  application:
    name: config-server #对应配置文件规则中的{application} 部分。
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BruceWhiteBai/cloudconfig.git
          username: BruceWhiteBai
          password: JohnCena3463125
          searchPaths: config-repo
      label: config_1 #对应配置文件规则中的{label} 部分。
      profile: dev  #对应配置文件规则中的{profile} 部分。

server:
  port: 8888
