server:
  port: 8781


eureka:
  client:
    service-url:
     defaultZone: http://admin:admin@localhost:8761/eureka,http://admin:admin@localhost:8762/eureka
spring:
  application:
    name: provider
