server:
  port: 8781


eureka:
  instance:
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 5
    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
     defaultZone: http://admin:admin@localhost:8761/eureka,http://admin:admin@localhost:8762/eureka
    #Eureka Serer会维护 一份只读的服务清单来返回给客户端，同时该缓存清单会每隔30秒更新 一次
    registry-fetch-interval-seconds: 30
spring:
  application:
    name: provider
